/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.projectamityandroidofficer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_tab_artists=0x7f020000;
        public static final int ic_tab_artists_grey=0x7f020001;
        public static final int ic_tab_artists_white=0x7f020002;
    }
    public static final class id {
        public static final int DateContent=0x7f05000b;
        public static final int DateTitle=0x7f05000a;
        public static final int DescriptionContent=0x7f05000d;
        public static final int DescriptionTitle=0x7f05000c;
        public static final int LoginButton=0x7f050006;
        public static final int LoginIDExitText=0x7f050003;
        public static final int LoginLinearLayour=0x7f050001;
        public static final int PasswordExitText=0x7f050005;
        public static final int PasswordTextView=0x7f050004;
        public static final int TitleContent=0x7f050009;
        public static final int TitleTitle=0x7f050008;
        public static final int loginIDTextView=0x7f050002;
        public static final int mapview=0x7f05000e;
        public static final int resolveOutDescriptionContent=0x7f050011;
        public static final int resolveOutDescriptionTitle=0x7f050010;
        public static final int resolveOutImageTitle=0x7f050014;
        public static final int resolveOutStatusContent=0x7f050013;
        public static final int resolveOutStatusTitle=0x7f050012;
        public static final int resolveOutdoorLayout=0x7f05000f;
        public static final int surface_camera=0x7f050000;
        public static final int widget38=0x7f050007;
    }
    public static final class layout {
        public static final int camera_surface=0x7f030000;
        public static final int main=0x7f030001;
        public static final int outdoorreport=0x7f030002;
        public static final int report=0x7f030003;
        public static final int resolveoutdoor=0x7f030004;
        public static final int taboutdoor=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
