/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.projectamityandroid;

public final class R {
    public static final class array {
        public static final int mainMenuOptions=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int cabpoolmapbluepin=0x7f020000;
        public static final int cabpoolmapredpin=0x7f020001;
        public static final int cabpoolmapyellowpin=0x7f020002;
        public static final int ic_tab_artists=0x7f020003;
        public static final int ic_tab_artists_grey=0x7f020004;
        public static final int ic_tab_artists_white=0x7f020005;
        public static final int ic_tab_car=0x7f020006;
        public static final int ic_tab_car_grey=0x7f020007;
        public static final int ic_tab_car_white=0x7f020008;
        public static final int ic_tab_mail=0x7f020009;
        public static final int ic_tab_mail_grey=0x7f02000a;
        public static final int ic_tab_mail_white=0x7f02000b;
    }
    public static final class id {
        public static final int ScrollViewIndoorReport=0x7f060008;
        public static final int ScrollViewOutdoorReport=0x7f060032;
        public static final int btnLogIn=0x7f06001b;
        public static final int btnbacktoinbox=0x7f060024;
        public static final int btndiscardnewmessage=0x7f060030;
        public static final int btnreplymessage=0x7f060025;
        public static final int btnsendnewmessage=0x7f060031;
        public static final int btnupdatecabpooldestination=0x7f060003;
        public static final int cabpoolMap=0x7f060004;
        public static final int cabpoolmain=0x7f060000;
        public static final int cabpoolupdatelocation=0x7f060001;
        public static final int composemessage=0x7f060027;
        public static final int composemessagebuttons=0x7f06002f;
        public static final int composemessagehead=0x7f060028;
        public static final int frmLogIn=0x7f060015;
        public static final int image=0x7f060006;
        public static final int indoorCamera=0x7f060012;
        public static final int indoorDescriptionContent=0x7f06000d;
        public static final int indoorDescriptionTitle=0x7f06000c;
        public static final int indoorImage=0x7f060011;
        public static final int indoorImageTitle=0x7f060010;
        public static final int indoorLocationContent=0x7f06000f;
        public static final int indoorLocationTitle=0x7f06000e;
        public static final int indoorSubmit=0x7f060014;
        public static final int indoorTitleContent=0x7f06000b;
        public static final int indoorTitleTitle=0x7f06000a;
        public static final int indoorreportbuttons=0x7f060013;
        public static final int indoorreporting=0x7f060009;
        public static final int layout_root=0x7f060005;
        public static final int lblLogIn=0x7f060016;
        public static final int lblPassword=0x7f060019;
        public static final int lblUserID=0x7f060017;
        public static final int lblcomposemessage=0x7f06002d;
        public static final int lblcomposesubject=0x7f06002b;
        public static final int lblcomposeto=0x7f060029;
        public static final int messaging=0x7f06001c;
        public static final int messaginghome=0x7f06001d;
        public static final int outdoorCamera=0x7f06003c;
        public static final int outdoorDescriptionContent=0x7f060037;
        public static final int outdoorDescriptionTitle=0x7f060036;
        public static final int outdoorImage=0x7f06003b;
        public static final int outdoorImageTitle=0x7f06003a;
        public static final int outdoorLocationContent=0x7f060039;
        public static final int outdoorLocationTitle=0x7f060038;
        public static final int outdoorSubmit=0x7f06003e;
        public static final int outdoorTitleContent=0x7f060035;
        public static final int outdoorTitleTitle=0x7f060034;
        public static final int outdoorreportbuttons=0x7f06003d;
        public static final int outdoorreporting=0x7f060033;
        public static final int tbxPassword=0x7f06001a;
        public static final int tbxUserID=0x7f060018;
        public static final int tbxcabpooldestination=0x7f060002;
        public static final int tbxcomposemessage=0x7f06002e;
        public static final int tbxcomposesubject=0x7f06002c;
        public static final int tbxcomposeto=0x7f06002a;
        public static final int tbxreplymessage=0x7f060022;
        public static final int text=0x7f060007;
        public static final int textView=0x7f06003f;
        public static final int viewmessage=0x7f06001e;
        public static final int viewmessagebuttons=0x7f060023;
        public static final int viewmessagehead=0x7f06001f;
        public static final int viewmessageheadchild=0x7f060020;
        public static final int viewmessagemain=0x7f060021;
        public static final int viewmessagemarkasread=0x7f060026;
    }
    public static final class layout {
        public static final int cabpool=0x7f030000;
        public static final int debug=0x7f030001;
        public static final int indoorreporting=0x7f030002;
        public static final int login=0x7f030003;
        public static final int main=0x7f030004;
        public static final int messaging=0x7f030005;
        public static final int outdoorreporting=0x7f030006;
        public static final int reporting=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
