/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.projectamityandroidofficer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_logout=0x7f020000;
        public static final int ic_tab_artists=0x7f020001;
        public static final int ic_tab_artists_grey=0x7f020002;
        public static final int ic_tab_artists_white=0x7f020003;
        public static final int markerpink=0x7f020004;
    }
    public static final class id {
        public static final int DateContent=0x7f060018;
        public static final int DateTitle=0x7f060017;
        public static final int DescriptionContent=0x7f06001a;
        public static final int DescriptionTitle=0x7f060019;
        public static final int IndoorDateContent=0x7f060005;
        public static final int IndoorDateTitle=0x7f060004;
        public static final int IndoorDescriptionContent=0x7f060007;
        public static final int IndoorDescriptionTitle=0x7f060006;
        public static final int IndoorPostalContent=0x7f060009;
        public static final int IndoorPostalTitle=0x7f060008;
        public static final int IndoorTitleContent=0x7f060003;
        public static final int IndoorTitleTitle=0x7f060002;
        public static final int Indoormapview=0x7f06000a;
        public static final int LoginButton=0x7f060013;
        public static final int LoginIDExitText=0x7f060010;
        public static final int LoginLinearLayour=0x7f06000e;
        public static final int PasswordExitText=0x7f060012;
        public static final int PasswordTextView=0x7f060011;
        public static final int TitleContent=0x7f060016;
        public static final int TitleTitle=0x7f060015;
        public static final int indoorRemove=0x7f06000b;
        public static final int loginIDTextView=0x7f06000f;
        public static final int logoutMenu=0x7f06002d;
        public static final int mapview=0x7f06000d;
        public static final int outdoorRemove=0x7f06001b;
        public static final int outdoorReportMap=0x7f06000c;
        public static final int resolveInCamera=0x7f060022;
        public static final int resolveInDescriptionContent=0x7f06001d;
        public static final int resolveInDescriptionTitle=0x7f06001c;
        public static final int resolveInImageContent=0x7f060021;
        public static final int resolveInImageTitle=0x7f060020;
        public static final int resolveInStatusContent=0x7f06001f;
        public static final int resolveInStatusTitle=0x7f06001e;
        public static final int resolveInSubmit=0x7f060023;
        public static final int resolveIndoorLayout=0x7f060001;
        public static final int resolveOutCamera=0x7f06002b;
        public static final int resolveOutDescriptionContent=0x7f060026;
        public static final int resolveOutDescriptionTitle=0x7f060025;
        public static final int resolveOutImageContent=0x7f06002a;
        public static final int resolveOutImageTitle=0x7f060029;
        public static final int resolveOutStatusContent=0x7f060028;
        public static final int resolveOutStatusTitle=0x7f060027;
        public static final int resolveOutSubmit=0x7f06002c;
        public static final int resolveOutdoorLayout=0x7f060024;
        public static final int surface_camera=0x7f060000;
        public static final int widget38=0x7f060014;
    }
    public static final class layout {
        public static final int camera_surface=0x7f030000;
        public static final int distancelist=0x7f030001;
        public static final int indoorreport=0x7f030002;
        public static final int locateofficer=0x7f030003;
        public static final int main=0x7f030004;
        public static final int outdoorreport=0x7f030005;
        public static final int report=0x7f030006;
        public static final int reportinghome=0x7f030007;
        public static final int resolveindoor=0x7f030008;
        public static final int resolveoutdoor=0x7f030009;
        public static final int tabindoor=0x7f03000a;
        public static final int taboutdoor=0x7f03000b;
    }
    public static final class menu {
        public static final int logout=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
